--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AtomicCityBuild/ShortGMCommands
build-by-default: true
branches:
- main
projects:
  ShortGMCommands:
    path: ""
    icon: "icon.png"
...
