name: ShortGMCommands
main: GermanLetsLPFor\Main
description: Shorter Gamemode Commands
author: GermanLetsLPFor
version: 2.5.16
api: 3.0.0
commands:
  gm:
    description: Change your Gamemode!
