# ShortGMCommands
#
# Thank you for using ShortGMCommands!
#
# The permission to use this plugin is
# just pocketmine.command.gamemode !
# Players without this default Gamemode 
# permission wont be able to use the
# commands.
#
# Please use " " for the messages.
# Otherwise it wont work

# --- Success Messages --- #
# GM Survival Change (/gm 0)
gmsurvival: "§aYour Gamemode has been changed to SURVIVAL!"

# GM Creative Change (/gm 1)
gmcreative: "§aYour Gamemode has been changed to CREATIVE!"

# GM Adventure Change (/gm 2)
gmadventure: "§aYour Gamemode has been changed to ADVENTURE!"

# GM Spectator Change (/gm 3)
gmspectator: "§aYour Gamemode has been changed to SPECTATOR!"


# --- Error Messages --- #
# If someone does not have the permission pocketmine.command.gamemode
nopermission: "§cYou dont have the permission to use this command"

# If the sender isnt a player
noplayer: "Please use this command Ingame!"